#!/bin/bash
set -e

# ═══════════════════════════════════════════════════════════════════════════════
# Oreuda APK Build Script — Run on the VPS (or locally with Flutter installed)
# ═══════════════════════════════════════════════════════════════════════════════
# Usage: bash build-apk.sh [branch_name]
#   branch_name — optional, used for naming the output folder

BRANCH="${1:-staging}"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BUILD_DIR="/root/oreuda/builds/${BRANCH}_${TIMESTAMP}"
LATEST_DIR="/root/oreuda/builds/latest"
PROJECT_DIR="/root/oreuda/frontend"

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "  🏗️  Oreuda APK Build — Branch: $BRANCH | Time: $TIMESTAMP"
echo "═══════════════════════════════════════════════════════════════════════════════"

# ── Ensure Flutter is installed ────────────────────────────────────────────────
FLUTTER_BIN="/opt/flutter/bin/flutter"
if [ ! -f "$FLUTTER_BIN" ]; then
    echo "📦 Flutter not found. Installing..."
    apt-get update -qq
    apt-get install -y -qq curl git unzip xz-utils zip libglu1-mesa openjdk-17-jdk-headless

    # Download stable Flutter (matches pubspec.yaml Dart SDK ^3.12.0)
    cd /opt
    curl -sSL "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.44.0-stable.tar.xz" | tar xJ
    export PATH="/opt/flutter/bin:$PATH"
    git config --global --add safe.directory /opt/flutter
    flutter config --no-analytics
    flutter doctor
else
    export PATH="/opt/flutter/bin:$PATH"
    git config --global --add safe.directory /opt/flutter
    echo "✅ Flutter found: $(flutter --version | head -1)"
fi

# ── Ensure Android SDK is installed ────────────────────────────────────────────
ANDROID_HOME="/opt/android-sdk"
if [ ! -d "$ANDROID_HOME/cmdline-tools" ]; then
    echo "📦 Android SDK not found. Installing..."
    mkdir -p "$ANDROID_HOME"
    cd "$ANDROID_HOME"

    # Download command line tools
    CMDLINE_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
    curl -sSL "$CMDLINE_TOOLS_URL" -o cmdline-tools.zip
    unzip -q cmdline-tools.zip
    mkdir -p cmdline-tools/latest
    mv cmdline-tools/bin cmdline-tools/lib cmdline-tools/NOTICE.txt cmdline-tools/source.properties cmdline-tools/latest/ 2>/dev/null || true
    rm -f cmdline-tools.zip

    export ANDROID_HOME
    export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

    # Accept licenses and install required SDK components
    yes | sdkmanager --licenses >/dev/null 2>&1 || true
    sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0" "ndk;27.0.12077973"
else
    export ANDROID_HOME
    export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"
    echo "✅ Android SDK found"
fi

# ── Pre-build: set production API URL ──────────────────────────────────────────
echo "⚙️  Injecting production API URL..."
mkdir -p "$BUILD_DIR"

# Create a build config that overrides the API host for release builds
# NOTE: Routes already include /api/v1 prefix, so baseUrl must NOT include it
cat > "$PROJECT_DIR/lib/config.dart" << 'EOF'
// AUTO-GENERATED by build-apk.sh — DO NOT EDIT MANUALLY
class BuildConfig {
  static const String apiHost = '37.60.229.74';
  static const String apiPort = '8004';
  static const String baseUrl = '';
}
EOF

echo "✅ Build config created with API: http://37.60.229.74:8004"

# ── Build the APK ──────────────────────────────────────────────────────────────
cd "$PROJECT_DIR"

echo "🔧 Running flutter pub get..."
flutter pub get

echo "🔨 Building release APK..."
flutter build apk --release \
    --dart-define=API_HOST=37.60.229.74 \
    --build-name="1.0.0" \
    --build-number="$(date +%s)"

# ── Copy output ────────────────────────────────────────────────────────────────
APK_SOURCE="$PROJECT_DIR/build/app/outputs/flutter-apk/app-release.apk"
APK_DEST="$BUILD_DIR/oreuda-release.apk"

cp "$APK_SOURCE" "$APK_DEST"

# Update "latest" symlink
rm -rf "$LATEST_DIR"
ln -s "$BUILD_DIR" "$LATEST_DIR"

# Save metadata
cat > "$BUILD_DIR/build-info.txt" << EOF
Branch: $BRANCH
Timestamp: $TIMESTAMP
Commit: $(cd /root/oreuda && git rev-parse --short HEAD)
API_URL: http://37.60.229.74:8004
Flutter: $(flutter --version | head -1)
EOF

echo "$APK_DEST" > /root/oreuda/builds/latest-apk-path.txt

# ── Done ───────────────────────────────────────────────────────────────────────
APK_SIZE=$(du -h "$APK_DEST" | cut -f1)

echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "  ✅ APK BUILD SUCCESSFUL"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "  📦 APK: $APK_DEST"
echo "  📏 Size: $APK_SIZE"
echo "  🔗 Latest symlink: $LATEST_DIR/oreuda-release.apk"
echo "  🌐 API Endpoint: http://37.60.229.74:8004"
echo "═══════════════════════════════════════════════════════════════════════════════"
