"""add last_decay_date to users

Revision ID: d9fd9183ff47
Revises: 001
Create Date: 2026-06-06 10:00:11.779704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9fd9183ff47'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dungeon_runs_user_id_fkey', 'dungeon_runs', type_='foreignkey')
    op.create_foreign_key(None, 'dungeon_runs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('guild_members_user_id_fkey', 'guild_members', type_='foreignkey')
    op.drop_constraint('guild_members_guild_id_fkey', 'guild_members', type_='foreignkey')
    op.create_foreign_key(None, 'guild_members', 'guilds', ['guild_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'guild_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('guilds_created_by_fkey', 'guilds', type_='foreignkey')
    op.create_foreign_key(None, 'guilds', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_health_snapshot_user_date', 'health_snapshots', ['user_id', 'date'])
    op.drop_constraint('health_snapshots_user_id_fkey', 'health_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'health_snapshots', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('inventory_items_user_id_fkey', 'inventory_items', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('lyfta_integrations_user_id_fkey', 'lyfta_integrations', type_='foreignkey')
    op.create_foreign_key(None, 'lyfta_integrations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('player_stats_user_id_fkey', 'player_stats', type_='foreignkey')
    op.create_foreign_key(None, 'player_stats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quest_completions_quest_id_fkey', 'quest_completions', type_='foreignkey')
    op.drop_constraint('quest_completions_user_id_fkey', 'quest_completions', type_='foreignkey')
    op.create_foreign_key(None, 'quest_completions', 'quests', ['quest_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quest_completions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quests_user_id_fkey', 'quests', type_='foreignkey')
    op.create_foreign_key(None, 'quests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('screentime_settings_user_id_fkey', 'screentime_settings', type_='foreignkey')
    op.create_foreign_key(None, 'screentime_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('titles_user_id_fkey', 'titles', type_='foreignkey')
    op.create_foreign_key(None, 'titles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('last_decay_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_decay_date')
    op.drop_constraint(None, 'titles', type_='foreignkey')
    op.create_foreign_key('titles_user_id_fkey', 'titles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'screentime_settings', type_='foreignkey')
    op.create_foreign_key('screentime_settings_user_id_fkey', 'screentime_settings', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'quests', type_='foreignkey')
    op.create_foreign_key('quests_user_id_fkey', 'quests', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'quest_completions', type_='foreignkey')
    op.drop_constraint(None, 'quest_completions', type_='foreignkey')
    op.create_foreign_key('quest_completions_user_id_fkey', 'quest_completions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('quest_completions_quest_id_fkey', 'quest_completions', 'quests', ['quest_id'], ['id'])
    op.drop_constraint(None, 'player_stats', type_='foreignkey')
    op.create_foreign_key('player_stats_user_id_fkey', 'player_stats', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'lyfta_integrations', type_='foreignkey')
    op.create_foreign_key('lyfta_integrations_user_id_fkey', 'lyfta_integrations', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.create_foreign_key('inventory_items_user_id_fkey', 'inventory_items', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'health_snapshots', type_='foreignkey')
    op.create_foreign_key('health_snapshots_user_id_fkey', 'health_snapshots', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_health_snapshot_user_date', 'health_snapshots', type_='unique')
    op.drop_constraint(None, 'guilds', type_='foreignkey')
    op.create_foreign_key('guilds_created_by_fkey', 'guilds', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'guild_members', type_='foreignkey')
    op.drop_constraint(None, 'guild_members', type_='foreignkey')
    op.create_foreign_key('guild_members_guild_id_fkey', 'guild_members', 'guilds', ['guild_id'], ['id'])
    op.create_foreign_key('guild_members_user_id_fkey', 'guild_members', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'dungeon_runs', type_='foreignkey')
    op.create_foreign_key('dungeon_runs_user_id_fkey', 'dungeon_runs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
